### ISSUE TITLE
VTB补

### ISSUE THREAD

**Issue by maoyalu** [bilibili-dd-center/vtbs.moe#28]
这里写上个人空间连接就行了

https://space.bilibili.com/588034
https://space.bilibili.com/178214

**Comment by simon300000** [comment]
咦，你是不是魔王YALU

**Comment by maoyalu** [comment]
是2333
昨天随便逛的时候没看到鹿木博士鹿太Channel就随手提了个issue

**Comment by simon300000** [comment]
谢谢咯233
