### ISSUE TITLE
VTB补（双子组替换）

### ISSUE THREAD

**Issue by aszx01018** [bilibili-dd-center/vtbs.moe#35]
这里写上个人空间连接就行了
https://space.bilibili.com/423728837

**Comment by simon300000** [comment]
这个需要把哪个给替换掉吗？

**Comment by aszx01018** [comment]
没说明清楚不好意思…
因为原组不再活动，所以进行了替换。
下面是需要替换的空间链接
https://space.bilibili.com/5847902

**Comment by simon300000** [comment]
OK
