### ISSUE TITLE
关于人气数据(bulkLive)接口

### ISSUE THREAD

**Issue by AFatOtaku** [bilibili-dd-center/vtbs.moe#46]
https://api.vtbs.moe/v2/bulkActive/:mid
关于人气和总播放量的接口可以正常获取
https://api.vtbs.moe/v2/bulkLive/:mid
但是关于直播人气的这个接口却提示Internal Server Error
请问是不提供直接获取吗？

(个人猜测应该是换了个路径直接从数据库获得了，然后这个接口废弃了？
然后人气是转接的观察者那边的所以还能用？)

**Comment by simon300000** [comment]
是的，人气接口我已经准备弃用了，目前人气使用的influxdb，性能比较差
虽然我内部还在用influx，但是已经准备弃用
https://github.com/bilibili-dd-center/vtbs.moe/blob/master/api/http.js#L65-L78

但是http用的是leveldb的人气接口，那个被我搞坏了...

我推荐使用api.vtb.wiki的接口，我也准备迁移人气的历史记录过去，改成按照直播场次查询 人气/弹幕 的形式
https://github.com/bilibili-dd-center/go-vtuber-wiki-api
https://api.vtb.wiki/swagger/
https://api.vtb.wiki/v2/bilibili/22ebf989-b3af-5efe-8d37-61772915073e/danmaku?time=1

**Comment by AFatOtaku** [comment]
十分感谢你的回答
那我的人气分析可能就要暂时延后一段时间了:(
不过你提供的其他接口对我十分有用，我又有了一些新的分析主意（兴奋）
感谢你分享的接口

其实那个接口也是我东翻西翻翻出来的，不好意思啦^_^

**Comment by simon300000** [comment]
嘿嘿 能帮上忙最好了
本来那个liveNum是个整数，bulkLive的长度
被我搞来搞去，现在带小数点了，然后就不能用了233

**Comment by AFatOtaku** [comment]
没事没事，真的十分感谢你！
我自己也有爬点数据，虽然不太全，但是勉强分析一下还是够得
有了这些数据，我以后的其他分析就有思路了

**Comment by simon300000** [comment]
有个QQ群，欢迎加入→_→！
663606562
