### ISSUE TITLE
关于如何处理转生势

### ISSUE THREAD

**Issue by simon300000** [bilibili-dd-center/vtbs.moe#5]
B站有许多转生势，如何处理转生势是个问题

总之问题还是：套个皮是不是就算是虚拟主播了？

说实在的，在Bilibili，在 <u>"哔哩哔哩直播，**二次元**弹幕直播平台"</u> 看到许多三次元就已经很神奇了，怎么来看，如果有vup/vtb直播，突然抢走小时榜，那是不是属于众望所归呢？

所以我在想网站上如何处理转生势，更多的是指

- 没有虚拟出道视频
- 不怎么用live2d或3d
- 没有设定，名字也不改

欢迎各位指点一下在下的迷津→_→！

**Comment by hzpwan** [comment]
冷鸟那个本身就带着人气的，但基本上除了直播和动态，她的视频基本和她的虚拟形象无关。
最近userlocal统计的有一个涨粉涨的很快的makeUmove，只玩VR游戏，视频或者直播都没有出过声。但她被划入转生势时，她也发了很多推特表示自己不是转生势，粉丝都是从用了虚拟形象之后才增加的。

所以我认为，是不是转生势，**这个就看他/她本身在用虚拟形象之前有没有带着人气吧，以及是否围绕着这个形象来运营吧**。

**Comment by simon300000** [comment]
是不是转生势其实不重要，我个人倒是也不歧视转生势什么的。主要就是不想“用过一次皮”就放进列表里。

像makeUmove那样至少在作为一个Vtuber运营那自然是可以放进来的
而有许多转生势会用皮直播，做视频；而且有明显的“虚拟主播出道”视频，所以我认为是可以划分为Vtuber

但是有些就是。。。那种，你懂的，我就不知道该怎么办23333

**Comment by MiracleXYZ** [comment]
这个其实是大家共同面对的问题……
UserLocal的处理方法是，转生势单独列一个组，不计入各种排行榜中。
但是如何界定转生组也是个问题……犬山这种刚开始可以被称为转生势，但是后来账号运营了这么久已经与普通的VTB差别不大了，只有统计油管/推特粉丝数据的时候有种时间穿越的感觉😂

**Comment by simon300000** [comment]
纯血VTB/混血VTB/疑似VTB/不是VTB
怎么感觉开始生草了233
有没有dalao训练一个神经网络来做个“VTB血统判定”作为基准

**Comment by wudifeixue** [comment]
我看了DDC那边判断基准，是70%的视频内容都有虚拟主播内容，那就可以判断为vtuber/vup了。  
如果大多数内容都不相关，强行上排行榜也比较尴尬吧？

**Comment by simon300000** [comment]
> 我看了DDC那边判断基准，是70%的视频内容都有虚拟主播内容，那就可以判断为vtuber/vup了。
> 如果大多数内容都不相关，强行上排行榜也比较尴尬吧？

这是一个好办法，我觉得可以加上一个时间限制，比如3个月内70%之类的。
然而有点难计算。。。
