### ISSUE TITLE
DD风云榜页面加载数据显示空白

### ISSUE THREAD

**Issue by NeroArc** [bilibili-dd-center/vtbs.moe#70]
DD风云榜控制台报错，页面空白。
this.vtbs.flat is not a function 
请检查代码

**Comment by simon300000** [comment]
您好，谢谢提交BUG

我需要以下信息尝试重现
系统平台：
浏览器，版本：

**Comment by NeroArc** [comment]
系统平台：Windows 7
浏览器：搜狗浏览器
版本：8.5

**Comment by simon300000** [comment]
完了，我用了老浏览器不支持的function，这个可能要等我搞个polyfill再请你测试一次

**Comment by simon300000** [comment]
要不换个浏览器（

**Comment by NeroArc** [comment]
OK，我用Chrome试了下，完全没问题。

**Comment by simon300000** [comment]
太好了，不用整polyfill了
